// -------------------------------------------------------------
// 
// File Name: hdlsrc\practical1_1\practical1_1.v
// Created: 2022-09-19 18:23:33
// 
// Generated by MATLAB 8.2 and HDL Coder 3.3
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0
// Target subsystem base rate: 0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: practical1_1
// Source Path: practical1_1
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module practical1_1
          (
           
          );




  real Constant_out1;  // double
  real Transfer_Fcn_out1;  // double

  // RANDOM TEXT



endmodule  // practical1_1

